# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0002_usertext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertext',
            name='tag',
            field=models.SlugField(unique=True),
        ),
    ]
