# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 18:11
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0004_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRCTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nct_id', models.TextField(unique=True)),
                ('updated_date', models.DateField()),
                ('date_trial_added', models.DateField()),
                ('brief_title', models.TextField()),
                ('title', models.TextField()),
                ('program_status', models.TextField()),
                ('phase', models.TextField()),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('gender', models.TextField()),
                ('inclusion_criteria', models.TextField()),
                ('exclusion_criteria', models.TextField()),
                ('locations', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('contact_phones', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('contact_emails', django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), size=None)),
                ('urls', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=300), size=None)),
                ('description', models.TextField()),
                ('is_crc_trial', models.BooleanField()),
                ('is_immunotherapy_trial', models.BooleanField()),
                ('comments', models.TextField()),
                ('publications', django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=300), size=None)),
                ('drug_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
        ),
    ]
