# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 18:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0006_crctrial_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctrial',
            name='brief_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='contact_phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), size=None),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='drug_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='gender',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='nct_id',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='phase',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='program_status',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
