# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0007_auto_20170310_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crctrial',
            old_name='approved',
            new_name='reviewed',
        ),
    ]
