# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 19:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0010_auto_20170310_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctrial',
            name='contact_emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='contact_phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='exclusion_criteria',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='inclusion_criteria',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='max_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='min_age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=300), null=True, size=None),
        ),
    ]
