# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 19:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0011_auto_20170310_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctrial',
            name='brief_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='drug_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
