# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 19:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0013_auto_20170310_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctrial',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='contact_phones',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), null=True, size=None),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='nct_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
