# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 19:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0015_auto_20170310_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='crctrial',
            name='intervention_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None),
        ),
    ]
