# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 22:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0016_crctrial_intervention_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctrial',
            name='category',
            field=models.CharField(max_length=100, verbose_name=b'Subtype'),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='is_crc_trial',
            field=models.BooleanField(default=False, verbose_name=b'CRC-directed trial'),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='is_immunotherapy_trial',
            field=models.BooleanField(default=False, verbose_name=b'Immunotherapy trial'),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='nct_id',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'NCT ID'),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='urls',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=300), null=True, size=None),
        ),
    ]
