# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 23:45
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0018_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctrial',
            name='gender',
            field=models.CharField(blank=True, choices=[(b'M', b'Male'), (b'F', b'Female'), (b'A', b'All')], max_length=1),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='locations',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, null=True), size=None),
        ),
    ]
