# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-13 22:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0022_auto_20170313_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctrial',
            name='resources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=250), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='trial_link',
            field=models.URLField(blank=True, help_text=b'Optional, defaults to the page at clinicaltrials.gov for this NCT ID', null=True),
        ),
    ]
