# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-16 13:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0023_auto_20170313_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptRuns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('record_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
