# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-21 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0025_crctrial_drug_brand_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedCRCTrial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateField(auto_now_add=True)),
                ('nct_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
