# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-31 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0026_deletedcrctrial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
