# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-25 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0027_delete_greeting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctrial',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
