# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-03 21:06
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0028_auto_20170425_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='crctrial',
            name='conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=300), blank=True, null=True, size=None),
        ),
    ]
