# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-28 01:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0031_auto_20171121_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crctrial',
            options={'permissions': (('phase_1', 'Phase 1 reviewer'), ('phase_2', 'Phase 2 reviewer'))},
        ),
    ]
