# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-28 01:41
from __future__ import unicode_literals

from django.db import migrations, models


def force_reviewed_null(apps, schema_editor):
    CRCTrial = apps.get_model('fightcrctrials', 'CRCTrial')
    for crctrial in CRCTrial.objects.filter(reviewed=False):
        crctrial.reviewed = None
        crctrial.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0032_auto_20171128_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crctrial',
            name='reviewed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.RunPython(force_reviewed_null)
    ]
