# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-28 01:56
from __future__ import unicode_literals

from django.db import migrations


def set_screened_for_reviewed(apps, schema_editor):
    CRCTrial = apps.get_model('fightcrctrials', 'CRCTrial')
    for crctrial in CRCTrial.objects.filter(reviewed=True):
        crctrial.screened = True
        crctrial.save()


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0033_auto_20171128_0141'),
    ]

    operations = [
        migrations.RunPython(set_screened_for_reviewed)
    ]
