# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-28 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0034_auto_20171128_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='crctrial',
            name='additional_review',
            field=models.BooleanField(default=False),
        ),
    ]
