# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-28 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0035_crctrial_additional_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='crctrial',
            name='review_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
