# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-06-23 18:24
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0036_crctrial_review_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='crctrial',
            name='keywords',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
