# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-15 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0038_mobilefaq'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileFAQ2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(unique=True)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Trial sub-type'),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='is_crc_trial',
            field=models.BooleanField(default=False, verbose_name='CRC-directed trial'),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='is_immunotherapy_trial',
            field=models.BooleanField(default=False, verbose_name='Immunotherapy trial'),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='nct_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='NCT ID'),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='phase',
            field=models.CharField(blank=True, choices=[('Phase 1', 'Phase 1'), ('Early Phase 1', 'Early Phase 1'), ('Phase 4', 'Phase 4'), ('Phase 1/Phase 2', 'Phase 1/Phase 2'), ('Phase 2/Phase 3', 'Phase 2/Phase 3'), ('Phase 2', 'Phase 2'), ('Phase 3', 'Phase 3')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='program_status',
            field=models.CharField(blank=True, choices=[('Temporarily not available', 'Temporarily not available'), ('Active, not recruiting', 'Active, not recruiting'), ('Suspended', 'Suspended'), ('Recruiting', 'Recruiting'), ('Withheld', 'Withheld'), ('Enrolling by invitation', 'Enrolling by invitation'), ('Completed', 'Completed'), ('No longer available', 'No longer available'), ('Unknown status', 'Unknown status'), ('Withdrawn', 'Withdrawn'), ('Available', 'Available'), ('Approved for marketing', 'Approved for marketing'), ('Not yet recruiting', 'Not yet recruiting'), ('Terminated', 'Terminated')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='trial_link',
            field=models.URLField(blank=True, help_text='Optional, defaults to the page at clinicaltrials.gov for this NCT ID', null=True),
        ),
    ]
