# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-15 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0039_auto_20190315_2355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crctrial',
            options={'permissions': (('phase_1', 'Phase 1 reviewer'), ('phase_2', 'Phase 2 reviewer')), 'verbose_name': 'CRC Trial', 'verbose_name_plural': 'CRC Trials'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name': 'FAQ', 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='mobilefaq2',
            options={'verbose_name': 'Mobile FAQ', 'verbose_name_plural': 'Mobile FAQs'},
        ),
        migrations.AlterField(
            model_name='crctrial',
            name='phase',
            field=models.CharField(blank=True, choices=[('N/A', 'N/A'), ('Phase 1', 'Phase 1'), ('Early Phase 1', 'Early Phase 1'), ('Phase 4', 'Phase 4'), ('Phase 1/Phase 2', 'Phase 1/Phase 2'), ('Phase 2/Phase 3', 'Phase 2/Phase 3'), ('Phase 2', 'Phase 2'), ('Phase 3', 'Phase 3')], max_length=20, null=True),
        ),
    ]
