# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models


def set_action_required(apps, schema_editor):
  Trials = apps.get_model('fightcrctrials', 'crctrial')
  for trial in Trials.objects.all().iterator():
    trial.action_required = 'Unknown' if trial.additional_review else None
    trial.save()

def reverse_action_required(apps, schema_editor):
  pass

class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0040_auto_20190415_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='crctrial',
            name='action_required',
            field=models.CharField(blank=True, choices=[(b'L1: Read', b'L1: Read'), (b'L2: Read', b'L2 Read'), (b'L2: Update COMM', b'L2: Update COMM'), (b'L2: Update LINKS', b'L2: Update LINKS'), (b'MAB: Review', b'MAB: Review'), (b'Unknown', b'Unknown')], default=None, max_length=100, null=True),
        ),
        migrations.RunPython(set_action_required, reverse_action_required)
    ]
