# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2021-01-04 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fightcrctrials', '0041_crctrial_action_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crctrial',
            name='additional_review',
        ),
    ]
